name: Train Model

on:
  push:
    branches: [ main ]
    paths: 
      - 'notebooks/'  # Dépand du projet
      - 'requirements.txt'
  workflow_dispatch:

# Ajouter les permissions nécessaires
permissions:
  contents: write
  actions: read

jobs:
  train:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'  # Sera changé en utilisant la version 3.10
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Train model
      run: |
        jupyter nbconvert --to script house_price_02_modelisation.ipynb
        python notebooks/house_price_02_modelisation.py
    
    - name: Upload model artifacts
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: |
          models/model.pkl
          models/metrics.pkl
        retention-days: 30
    
    - name: Commit and push model
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add models/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update trained model [skip ci]"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
        fi