name: Test Model

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Prepare data
      working-directory: notebooks
      run: |
        jupyter nbconvert --to script house_price_01_data_processing.ipynb
        python house_price_01_data_processing.py

    - name: Train model
      working-directory: notebooks
      env:
        MLFLOW_TRACKING_URI: file:./mlruns  # on redirige MLflow
      run: |
        jupyter nbconvert --to script house_price_02_modelisation.ipynb
        python house_price_02_modelisation.py

    - name: Run tests
      run: |
        python -m pytest tests/ -v
